// <auto-generated />
using System;
using AeroTech.Ordering.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ordering.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260924005837_AddFarePricingUnits")]
    partial class AddFarePricingUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Order")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentReservationAggregate.Entities.ReservationUnit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("FulfillmentReservationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("ObservedSeat")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.PrimitiveCollection<string>("OrderServiceIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderUnitRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RawStatusCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnitCorrelationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FulfillmentReservationId", "UnitCorrelationKey")
                        .IsUnique();

                    b.ToTable("ReservationUnits", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentReservationAggregate.FulfillmentReservation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FulfillmentProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderOperationRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("RequestedExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("FulfillmentReservations", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.Entities.FulfillmentTaskAttempt", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("FailureKind")
                        .HasColumnType("int");

                    b.Property<int?>("FailureReason")
                        .HasColumnType("int");

                    b.Property<long>("FulfillmentTaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("Outcome")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FulfillmentTaskId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("FulfillmentTaskAttempts", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.Entities.FulfillmentTaskTarget", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<long>("FulfillmentTaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservationUnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FulfillmentTaskId");

                    b.HasIndex("ReservationUnitId");

                    b.ToTable("FulfillmentTaskTargets", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.Entities.ProviderInteraction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("FulfillmentTaskId")
                        .HasColumnType("bigint");

                    b.Property<int>("InteractionType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("ProviderStatusCode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FulfillmentTaskId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("ProviderInteractions", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.FulfillmentTask", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FulfillmentProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("FulfillmentReservationId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("LastFailureKind")
                        .HasColumnType("int");

                    b.Property<int?>("LastFailureReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("FulfillmentReservationId", "TaskType");

                    b.ToTable("FulfillmentTasks", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<int>("CommercialVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CommercialVersion");

                    b.ToTable("OrderChanges", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContact", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderContacts", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContactPoint", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderContactId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrderContactId");

                    b.ToTable("OrderContactPoints", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderFareComponent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AirFareId")
                        .HasColumnType("bigint");

                    b.Property<string>("BookingClass")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.PrimitiveCollection<string>("CoveredOrderServiceIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FareBasis")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FareFamily")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FareType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderFarePricingUnitId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderFarePricingUnitId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderFareComponents", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderFarePricingUnit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("CoveredJourneyIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderFarePricingUnits", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AcceptedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CommercialStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByChangeId");

                    b.HasIndex("OrderId", "CommercialStatus");

                    b.ToTable("OrderItems", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderJourney", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BoundId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderJourneys", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderRemark", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrintedOnInvoice")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrintedOnItinerary")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderServiceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<long?>("SegmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("SupersedesRemarkId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("TravellerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupersedesRemarkId");

                    b.HasIndex("OrderId", "Status");

                    b.ToTable("OrderRemarks", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationAirportTerminalId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<long>("FlightId")
                        .HasColumnType("bigint");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("FlightVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("MarketingAirlineId")
                        .HasColumnType("int");

                    b.Property<int>("OperatingAirlineId")
                        .HasColumnType("int");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderJourneyId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginAirportTerminalId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SoldArrival")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SoldDeparture")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderJourneyId");

                    b.ToTable("OrderSegments", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegmentLeg", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ArrivalDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DepartureDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationAirportTerminalId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("LegId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderSegmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginAirportTerminalId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("StopDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool?>("StopPassengersCanBoardOrLeave")
                        .HasColumnType("bit");

                    b.Property<int?>("StopType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderSegmentId", "Sequence")
                        .IsUnique();

                    b.ToTable("OrderSegmentLegs", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("CommercialStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FulfillmentProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<long>("TravellerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("TravellerId");

                    b.HasIndex("OrderId", "CommercialStatus");

                    b.ToTable("OrderServices", "Order");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AgeRange")
                        .HasColumnType("int");

                    b.Property<long>("CurrentProfileRevisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<long?>("InfantParentTravellerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("PassengerType")
                        .HasColumnType("int");

                    b.Property<string>("SourceTravellerRef")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InfantParentTravellerId");

                    b.HasIndex("OrderId", "Index")
                        .IsUnique();

                    b.ToTable("OrderTravellers", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTravellerDocument", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Holder")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("IssuanceCountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("OrderTravellerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderTravellerId");

                    b.ToTable("OrderTravellerDocuments", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingAllocation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("EquivalentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EquivalentCurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderJourneyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderSegmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("PricingLineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TravellerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("OrderServiceId");

                    b.HasIndex("PricingLineId");

                    b.HasIndex("TravellerId");

                    b.ToTable("PricingAllocations", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("EquivalentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EquivalentCurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("Refundability")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int>("SubCategory")
                        .HasColumnType("int");

                    b.Property<int>("Treatment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByChangeId");

                    b.HasIndex("OrderId", "Treatment");

                    b.ToTable("PricingLines", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.TravellerProfileRevision", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("CountryOfResidenceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CreatedByChangeId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<bool>("NoSurname")
                        .HasColumnType("bit");

                    b.Property<long?>("SupersededByChangeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Surname")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("TravellerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByChangeId");

                    b.HasIndex("TravellerId");

                    b.ToTable("TravellerProfileRevisions", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("CommercialVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CustomerTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("LastTicketingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OrderReference")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecordLocator")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceOfferId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LastTicketingDate");

                    b.HasIndex("OrderReference")
                        .IsUnique();

                    b.HasIndex("RecordLocator")
                        .IsUnique()
                        .HasFilter("[RecordLocator] IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("Orders", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("ReceivedOn");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ordering.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderAirTransportService", b =>
                {
                    b.HasBaseType("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService");

                    b.Property<long?>("AirFareId")
                        .HasColumnType("bigint");

                    b.Property<string>("BookingClass")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("FareBasis")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FareFamily")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FareType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("FlightCapacityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsChangeable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefundable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUpgradable")
                        .HasColumnType("bit");

                    b.Property<long?>("RbdId")
                        .HasColumnType("bigint");

                    b.Property<long>("SegmentId")
                        .HasColumnType("bigint");

                    b.HasIndex("SegmentId");

                    b.ToTable("OrderAirTransportServices", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSeatService", b =>
                {
                    b.HasBaseType("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService");

                    b.Property<long>("AssociatedAirServiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("SegmentId")
                        .HasColumnType("bigint");

                    b.HasIndex("AssociatedAirServiceId");

                    b.HasIndex("SegmentId");

                    b.ToTable("OrderSeatServices", "Order");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentReservationAggregate.Entities.ReservationUnit", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.FulfillmentReservationAggregate.FulfillmentReservation", null)
                        .WithMany("Units")
                        .HasForeignKey("FulfillmentReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.Entities.FulfillmentTaskAttempt", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.FulfillmentTask", null)
                        .WithMany("Attempts")
                        .HasForeignKey("FulfillmentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.Entities.FulfillmentTaskTarget", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.FulfillmentTask", null)
                        .WithMany("Targets")
                        .HasForeignKey("FulfillmentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.Entities.ProviderInteraction", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.FulfillmentTask", null)
                        .WithMany("Interactions")
                        .HasForeignKey("FulfillmentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderChange", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Changes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.SalesContext", "ActorContext", b1 =>
                        {
                            b1.Property<long>("OrderChangeId")
                                .HasColumnType("bigint");

                            b1.Property<long>("ActorId")
                                .HasColumnType("bigint")
                                .HasColumnName("ActorId");

                            b1.Property<long?>("AirlineUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ActorAirlineUserId");

                            b1.Property<int>("Channel")
                                .HasColumnType("int")
                                .HasColumnName("ActorChannel");

                            b1.Property<int>("ContextType")
                                .HasColumnType("int")
                                .HasColumnName("ActorContextType");

                            b1.Property<long?>("IndividualId")
                                .HasColumnType("bigint")
                                .HasColumnName("ActorIndividualId");

                            b1.Property<long?>("OfficeId")
                                .HasColumnType("bigint")
                                .HasColumnName("ActorOfficeId");

                            b1.Property<int?>("OfficeKind")
                                .HasColumnType("int")
                                .HasColumnName("ActorOfficeKind");

                            b1.Property<long?>("PartnerApiAccessProfileId")
                                .HasColumnType("bigint")
                                .HasColumnName("ActorPartnerApiAccessProfileId");

                            b1.Property<int>("PrincipalType")
                                .HasColumnType("int")
                                .HasColumnName("ActorPrincipalType");

                            b1.Property<long?>("TravelAgencyId")
                                .HasColumnType("bigint")
                                .HasColumnName("ActorTravelAgencyId");

                            b1.Property<long?>("TravelAgencyUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ActorTravelAgencyUserId");

                            b1.HasKey("OrderChangeId");

                            b1.ToTable("OrderChanges", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderChangeId");
                        });

                    b.Navigation("ActorContext")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContact", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Contacts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContactPoint", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContact", null)
                        .WithMany("ContactPoints")
                        .HasForeignKey("OrderContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderFareComponent", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderFarePricingUnit", null)
                        .WithMany("FareComponents")
                        .HasForeignKey("OrderFarePricingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderFarePricingUnit", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("FarePricingUnits")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderJourney", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Journeys")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderRemark", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Remarks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Segments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegmentLeg", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", null)
                        .WithMany("Legs")
                        .HasForeignKey("OrderSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Services")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("Travellers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTravellerDocument", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", null)
                        .WithMany("Documents")
                        .HasForeignKey("OrderTravellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingAllocation", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", null)
                        .WithMany("Allocations")
                        .HasForeignKey("PricingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Order", null)
                        .WithMany("PricingLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.ExchangeRateSnapshot", "ExchangeRateSnapshot", b1 =>
                        {
                            b1.Property<long>("PricingLineId")
                                .HasColumnType("bigint");

                            b1.Property<int>("DecimalPlaces")
                                .HasColumnType("int")
                                .HasColumnName("ExchangeDecimalPlaces");

                            b1.Property<int>("FromCurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("ExchangeFromCurrencyId");

                            b1.Property<string>("PeriodId")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("ExchangePeriodId");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(19, 9)
                                .HasColumnType("decimal(19,9)")
                                .HasColumnName("ExchangeRate");

                            b1.Property<int>("ToCurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("ExchangeToCurrencyId");

                            b1.HasKey("PricingLineId");

                            b1.ToTable("PricingLines", "Order");

                            b1.WithOwner()
                                .HasForeignKey("PricingLineId");
                        });

                    b.Navigation("ExchangeRateSnapshot");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.TravellerProfileRevision", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", null)
                        .WithMany("ProfileRevisions")
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.SalesContext", "SalesContext", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("bigint");

                            b1.Property<long>("ActorId")
                                .HasColumnType("bigint")
                                .HasColumnName("SalesActorId");

                            b1.Property<long?>("AirlineUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("SalesAirlineUserId");

                            b1.Property<int>("Channel")
                                .HasColumnType("int")
                                .HasColumnName("SalesChannel");

                            b1.Property<int>("ContextType")
                                .HasColumnType("int")
                                .HasColumnName("SalesContextType");

                            b1.Property<long?>("IndividualId")
                                .HasColumnType("bigint")
                                .HasColumnName("SalesIndividualId");

                            b1.Property<long?>("OfficeId")
                                .HasColumnType("bigint")
                                .HasColumnName("SalesOfficeId");

                            b1.Property<int?>("OfficeKind")
                                .HasColumnType("int")
                                .HasColumnName("SalesOfficeKind");

                            b1.Property<long?>("PartnerApiAccessProfileId")
                                .HasColumnType("bigint")
                                .HasColumnName("SalesPartnerApiAccessProfileId");

                            b1.Property<int>("PrincipalType")
                                .HasColumnType("int")
                                .HasColumnName("SalesPrincipalType");

                            b1.Property<long?>("TravelAgencyId")
                                .HasColumnType("bigint")
                                .HasColumnName("SalesTravelAgencyId");

                            b1.Property<long?>("TravelAgencyUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("SalesTravelAgencyUserId");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("SalesContext")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderAirTransportService", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", null)
                        .WithOne()
                        .HasForeignKey("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderAirTransportService", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.BaggageAllowance", "CabinBaggageAllowance", b1 =>
                        {
                            b1.Property<long>("OrderAirTransportServiceId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Pieces")
                                .HasColumnType("int")
                                .HasColumnName("CabinBaggagePieces");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("CabinBaggageUnit");

                            b1.Property<decimal>("Weight")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CabinBaggageWeight");

                            b1.HasKey("OrderAirTransportServiceId");

                            b1.ToTable("OrderAirTransportServices", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderAirTransportServiceId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.BaggageAllowance", "CheckedBaggageAllowance", b1 =>
                        {
                            b1.Property<long>("OrderAirTransportServiceId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Pieces")
                                .HasColumnType("int")
                                .HasColumnName("CheckedBaggagePieces");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("CheckedBaggageUnit");

                            b1.Property<decimal>("Weight")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CheckedBaggageWeight");

                            b1.HasKey("OrderAirTransportServiceId");

                            b1.ToTable("OrderAirTransportServices", "Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderAirTransportServiceId");
                        });

                    b.Navigation("CabinBaggageAllowance");

                    b.Navigation("CheckedBaggageAllowance");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSeatService", b =>
                {
                    b.HasOne("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderService", null)
                        .WithOne()
                        .HasForeignKey("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSeatService", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentReservationAggregate.FulfillmentReservation", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.FulfillmentTaskAggregate.FulfillmentTask", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Interactions");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderContact", b =>
                {
                    b.Navigation("ContactPoints");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderFarePricingUnit", b =>
                {
                    b.Navigation("FareComponents");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderSegment", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderTraveller", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ProfileRevisions");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Entities.PricingLine", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Contacts");

                    b.Navigation("FarePricingUnits");

                    b.Navigation("Items");

                    b.Navigation("Journeys");

                    b.Navigation("PricingLines");

                    b.Navigation("Remarks");

                    b.Navigation("Segments");

                    b.Navigation("Services");

                    b.Navigation("Travellers");
                });
#pragma warning restore 612, 618
        }
    }
}
